name: 'Build and Push to ECR'
description: 'Build Docker image and push to ECR in Operations account'

inputs:
  aws-account-id:
    description: 'AWS account ID for ECR'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  ecr-repo-name:
    description: 'ECR repository name'
    required: true
  image-tag:
    description: 'Image tag to use'
    required: true
  role-to-assume:
    description: 'IAM role ARN to assume'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  platform:
    description: 'Target platform (linux/amd64 or linux/arm64)'
    required: false
    default: 'linux/arm64'

outputs:
  image-uri:
    description: 'Full ECR image URI'
    value: ${{ steps.build.outputs.image-uri }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        audience: sts.amazonaws.com

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      id: build
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:${{ inputs.image-tag }}"
        docker buildx build --platform ${{ inputs.platform }} -t $IMAGE_URI -f ${{ inputs.dockerfile }} ${{ inputs.context }} --push
        echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT
